package input

import (
	// Ebitengine
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
)

// Keys.
const (
	KeyA              int = int(ebiten.KeyA)
	KeyB              int = int(ebiten.KeyB)
	KeyC              int = int(ebiten.KeyC)
	KeyD              int = int(ebiten.KeyD)
	KeyE              int = int(ebiten.KeyE)
	KeyF              int = int(ebiten.KeyF)
	KeyG              int = int(ebiten.KeyG)
	KeyH              int = int(ebiten.KeyH)
	KeyI              int = int(ebiten.KeyI)
	KeyJ              int = int(ebiten.KeyJ)
	KeyK              int = int(ebiten.KeyK)
	KeyL              int = int(ebiten.KeyL)
	KeyM              int = int(ebiten.KeyM)
	KeyN              int = int(ebiten.KeyN)
	KeyO              int = int(ebiten.KeyO)
	KeyP              int = int(ebiten.KeyP)
	KeyQ              int = int(ebiten.KeyQ)
	KeyR              int = int(ebiten.KeyR)
	KeyS              int = int(ebiten.KeyS)
	KeyT              int = int(ebiten.KeyT)
	KeyU              int = int(ebiten.KeyU)
	KeyV              int = int(ebiten.KeyV)
	KeyW              int = int(ebiten.KeyW)
	KeyX              int = int(ebiten.KeyX)
	KeyY              int = int(ebiten.KeyY)
	KeyZ              int = int(ebiten.KeyZ)
	KeyAltLeft        int = int(ebiten.KeyAltLeft)
	KeyAltRight       int = int(ebiten.KeyAltRight)
	KeyArrowDown      int = int(ebiten.KeyArrowDown)
	KeyArrowLeft      int = int(ebiten.KeyArrowLeft)
	KeyArrowRight     int = int(ebiten.KeyArrowRight)
	KeyArrowUp        int = int(ebiten.KeyArrowUp)
	KeyBackquote      int = int(ebiten.KeyBackquote)
	KeyBackslash      int = int(ebiten.KeyBackslash)
	KeyBackspace      int = int(ebiten.KeyBackspace)
	KeyBracketLeft    int = int(ebiten.KeyBracketLeft)
	KeyBracketRight   int = int(ebiten.KeyBracketRight)
	KeyCapsLock       int = int(ebiten.KeyCapsLock)
	KeyComma          int = int(ebiten.KeyComma)
	KeyContextMenu    int = int(ebiten.KeyContextMenu)
	KeyControlLeft    int = int(ebiten.KeyControlLeft)
	KeyControlRight   int = int(ebiten.KeyControlRight)
	KeyDelete         int = int(ebiten.KeyDelete)
	KeyDigit0         int = int(ebiten.KeyDigit0)
	KeyDigit1         int = int(ebiten.KeyDigit1)
	KeyDigit2         int = int(ebiten.KeyDigit2)
	KeyDigit3         int = int(ebiten.KeyDigit3)
	KeyDigit4         int = int(ebiten.KeyDigit4)
	KeyDigit5         int = int(ebiten.KeyDigit5)
	KeyDigit6         int = int(ebiten.KeyDigit6)
	KeyDigit7         int = int(ebiten.KeyDigit7)
	KeyDigit8         int = int(ebiten.KeyDigit8)
	KeyDigit9         int = int(ebiten.KeyDigit9)
	KeyEnd            int = int(ebiten.KeyEnd)
	KeyEnter          int = int(ebiten.KeyEnter)
	KeyEqual          int = int(ebiten.KeyEqual)
	KeyEscape         int = int(ebiten.KeyEscape)
	KeyF1             int = int(ebiten.KeyF1)
	KeyF2             int = int(ebiten.KeyF2)
	KeyF3             int = int(ebiten.KeyF3)
	KeyF4             int = int(ebiten.KeyF4)
	KeyF5             int = int(ebiten.KeyF5)
	KeyF6             int = int(ebiten.KeyF6)
	KeyF7             int = int(ebiten.KeyF7)
	KeyF8             int = int(ebiten.KeyF8)
	KeyF9             int = int(ebiten.KeyF9)
	KeyF10            int = int(ebiten.KeyF10)
	KeyF11            int = int(ebiten.KeyF11)
	KeyF12            int = int(ebiten.KeyF12)
	KeyF13            int = int(ebiten.KeyF13)
	KeyF14            int = int(ebiten.KeyF14)
	KeyF15            int = int(ebiten.KeyF15)
	KeyF16            int = int(ebiten.KeyF16)
	KeyF17            int = int(ebiten.KeyF17)
	KeyF18            int = int(ebiten.KeyF18)
	KeyF19            int = int(ebiten.KeyF19)
	KeyF20            int = int(ebiten.KeyF20)
	KeyF21            int = int(ebiten.KeyF21)
	KeyF22            int = int(ebiten.KeyF22)
	KeyF23            int = int(ebiten.KeyF23)
	KeyF24            int = int(ebiten.KeyF24)
	KeyHome           int = int(ebiten.KeyHome)
	KeyInsert         int = int(ebiten.KeyInsert)
	KeyIntlBackslash  int = int(ebiten.KeyIntlBackslash)
	KeyMetaLeft       int = int(ebiten.KeyMetaLeft)
	KeyMetaRight      int = int(ebiten.KeyMetaRight)
	KeyMinus          int = int(ebiten.KeyMinus)
	KeyNumLock        int = int(ebiten.KeyNumLock)
	KeyNumpad0        int = int(ebiten.KeyNumpad0)
	KeyNumpad1        int = int(ebiten.KeyNumpad1)
	KeyNumpad2        int = int(ebiten.KeyNumpad2)
	KeyNumpad3        int = int(ebiten.KeyNumpad3)
	KeyNumpad4        int = int(ebiten.KeyNumpad4)
	KeyNumpad5        int = int(ebiten.KeyNumpad5)
	KeyNumpad6        int = int(ebiten.KeyNumpad6)
	KeyNumpad7        int = int(ebiten.KeyNumpad7)
	KeyNumpad8        int = int(ebiten.KeyNumpad8)
	KeyNumpad9        int = int(ebiten.KeyNumpad9)
	KeyNumpadAdd      int = int(ebiten.KeyNumpadAdd)
	KeyNumpadDecimal  int = int(ebiten.KeyNumpadDecimal)
	KeyNumpadDivide   int = int(ebiten.KeyNumpadDivide)
	KeyNumpadEnter    int = int(ebiten.KeyNumpadEnter)
	KeyNumpadEqual    int = int(ebiten.KeyNumpadEqual)
	KeyNumpadMultiply int = int(ebiten.KeyNumpadMultiply)
	KeyNumpadSubtract int = int(ebiten.KeyNumpadSubtract)
	KeyPageDown       int = int(ebiten.KeyPageDown)
	KeyPageUp         int = int(ebiten.KeyPageUp)
	KeyPause          int = int(ebiten.KeyPause)
	KeyPeriod         int = int(ebiten.KeyPeriod)
	KeyPrintScreen    int = int(ebiten.KeyPrintScreen)
	KeyQuote          int = int(ebiten.KeyQuote)
	KeyScrollLock     int = int(ebiten.KeyScrollLock)
	KeySemicolon      int = int(ebiten.KeySemicolon)
	KeyShiftLeft      int = int(ebiten.KeyShiftLeft)
	KeyShiftRight     int = int(ebiten.KeyShiftRight)
	KeySlash          int = int(ebiten.KeySlash)
	KeySpace          int = int(ebiten.KeySpace)
	KeyTab            int = int(ebiten.KeyTab)
	KeyAlt            int = int(ebiten.KeyTab)
	KeyControl        int = int(ebiten.KeyControl)
	KeyShift          int = int(ebiten.KeyShift)
	KeyMeta           int = int(ebiten.KeyMeta)
	KeyMax            int = int(ebiten.KeyMax)
)

const (
	MouseButtonLeft   int = int(ebiten.MouseButton0)
	MouseButtonMiddle int = int(ebiten.MouseButton1)
	MouseButtonRight  int = int(ebiten.MouseButton2)

	MouseButton0   int = int(ebiten.MouseButton0)
	MouseButton1   int = int(ebiten.MouseButton1)
	MouseButton2   int = int(ebiten.MouseButton2)
	MouseButton3   int = int(ebiten.MouseButton3)
	MouseButton4   int = int(ebiten.MouseButton4)
	MouseButtonMax int = int(ebiten.MouseButton4)
)

func IsKeyDown(key int) bool {
	return ebiten.IsKeyPressed(ebiten.Key(key))
}

func IsKeyPressed(key int) bool {
	return inpututil.IsKeyJustPressed(ebiten.Key(key))
}

func IsMouseButtonPressed(mouseButton int) bool {
	return inpututil.IsMouseButtonJustPressed(ebiten.MouseButton(mouseButton))
}

func IsMouseButtonDown(mouseButton int) bool {
	return ebiten.IsMouseButtonPressed(ebiten.MouseButton(mouseButton))
}
